In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

import seaborn as sns
import matplotlib.pyplot as plt

import sklearn as sk
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.calibration import calibration_curve
from sklearn.metrics import log_loss
from sklearn.metrics import brier_score_loss
from sklearn.model_selection import cross_val_score

In [5]:
games = pd.read_csv('games_new_vars.csv')

In [6]:
games.columns

Index(['Unnamed: 0', 'id', 'rated', 'created_at', 'last_move_at', 'turns',
       'victory_status', 'winner', 'increment_code', 'white_id',
       'white_rating', 'black_id', 'black_rating', 'moves', 'opening_eco',
       'opening_name', 'opening_ply', 'diff_rating', 'abs_diff_rating',
       'higher_rating', 'higher_rating_won', 'higher_rating_coded',
       'white_higher_rated', 'result'],
      dtype='object')

In [6]:
# Create a new variable for the difference in rating between two players.
games['diff_rating'] = games.white_rating - games.black_rating

In [7]:
# Create a new variable with absolute value of differences
games['abs_diff_rating'] = np.abs(games['diff_rating'])

In [8]:
# Create new key
# -- higher_rating will encode who has the higher rating. 
games['higher_rating'] = ''

In [11]:
# Given the organization of the data, positive differences in the diff_rating indicate white had a higher rating, 
# whereas negative ones indicated a higher rating for black. A difference of zero, of course, indicates an equal rating. 
games.loc[games.diff_rating > 0, 'higher_rating'] = 'white'
games.loc[games.diff_rating < 0, 'higher_rating'] = 'black'
games.loc[games.diff_rating == 0, 'higher_rating'] = 'same'

In [14]:
# ** We need to clean this code up
# Now, we encode a variable that returns 1 if the higher rating won and 0 otherwise. 
games['hr_won'] = 0
for i in list(range(len(games))):
    if games.higher_rating[i] == games.winner[i]:
        games.hr_won[i] = 1
    else:
        games.hr_won[i] = 0

/Users/Leonard/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/Leonard/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [48]:
# ** We need to clean this code up
# Also need to code higher rating as a binary so that we can easily use it 
games['higher_rating_coded'] = 0
for i in list(range(len(games))):
    if games.higher_rating[i] == 'white':
        games.higher_rating_coded[i] = 1
    else: # Note that I'm ignoring draws with this type of analysis, rn, in the moment.
        games.higher_rating_coded[i] = 0

/Users/Leonard/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/Users/Leonard/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Learning how to use kfold cross validation

In [41]:
X = games[['abs_diff_rating']]
Y = games.hr_won

In [42]:
lg = LogisticRegression()

In [45]:
lg_scores = cross_val_score(lg, X, Y , cv=10)

In [4]:
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_spli

In [49]:
lg_scores.mean()

0.6274804762769048

Done learning how to use kfold cross validation. 

In [60]:
kf =KFold( n_splits = 5)

In [61]:
for train, test in kf.split(X, Y):
    print(train)
    print(test)

[ 4012  4013  4014 ... 20055 20056 20057]
[   0    1    2 ... 4009 4010 4011]
[    0     1     2 ... 20055 20056 20057]
[4012 4013 4014 ... 8021 8022 8023]
[    0     1     2 ... 20055 20056 20057]
[ 8024  8025  8026 ... 12033 12034 12035]
[    0     1     2 ... 20055 20056 20057]
[12036 12037 12038 ... 16044 16045 16046]
[    0     1     2 ... 16044 16045 16046]
[16047 16048 16049 ... 20055 20056 20057]


In [54]:
train, test = kf.split(X, Y)

ValueError: too many values to unpack (expected 2)